ticket 10
ellamarym/fe-nc-news pull request #8
Opened 2022-12-08 14:06 UTC by ellamarym

2022-12-08 14:56 UTC, cjplatten reviewed
The sorting doesn't always work. Please see comments and submit another PR once you have made changes.

2022-12-08 14:56 UTC, cjplatten commented on src/components/ArticleList.jsx
> +        if(queries.length){
This if block and the previous if/else block are **both** running, meaning setArticlesList is being set twice, resulting in the articles not always being sorted.

2022-12-08 15:31 UTC, callumu21 requested changes
Ticket #11 - Deleting comments: Works as expected and is good to merge!

Ticket #10 - Sorting articles: Just need to refactor your axios requests into a single fetch using request config to control the optional queries 👍

2022-12-09 11:52 UTC, cjplatten reviewed
please see comment. 
There are also some warnings showing up in the console that it would be good to have a look at fixing

2022-12-09 11:52 UTC, cjplatten commented on src/components/ArticleList.jsx
> +                    <option value='placeholder'></option>
the way that this is constructed means that if this placeholder is selected it sends a query to the api of "topic={topic}&placeholder"

2022-12-09 13:49 UTC, merged